# PLACEHOLDER - Generated by install.sh
# This file will be overwritten with your actual configuration
{
  username = "changeme";
  fullName = "Change Me";
  email = "changeme@example.com";
  timezone = "Africa/Johannesburg";
  locale = "en_ZA.UTF-8";
}
