#!/usr/bin/env bash
# NixOS COSMIC Installation Script
set -eo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration
REPO_URL="https://github.com/JulianPasco/cosmic-nix"
INSTALL_DIR="/etc/nixos"

# Banner
echo -e "${CYAN}"
cat << "EOF"
   ____  ___  ____  __  __  ___  ____    _   _ ___ __  __
  / ___|/ _ \/ ___||  \/  |/ _ \/ ___|  | \ | |_ _|\ \/ /
 | |  | | | \___ \| |\/| | | | \___ \  |  \| || |  \  / 
 | |__| |_| |___) | |  | | |_| |___) | | |\  || |  /  \ 
  \____\___/|____/|_|  |_|\___/|____/  |_| \_|___/_/\_\
                                                         
  NixOS + COSMIC Desktop Installer
EOF
echo -e "${NC}"

# Checks
if [ "$EUID" -eq 0 ]; then
    echo -e "${RED}Error: Do not run this script as root${NC}"
    echo "Run as your normal user. Sudo will be used when needed."
    exit 1
fi

if [ ! -f /etc/NIXOS ]; then
    echo -e "${RED}Error: This script must be run on NixOS${NC}"
    echo "Please install NixOS first: https://nixos.org/download"
    exit 1
fi

echo -e "${BLUE}Welcome to the NixOS COSMIC installer${NC}"
echo ""

# Collect user information (read from /dev/tty to work with piped input)
echo -e "${CYAN}Let's configure your system${NC}"
echo ""

# Check for existing configuration to reuse
if [ -f "$INSTALL_DIR/user-config.nix" ]; then
    # Extract values using grep and cut (assuming standard format generated by this script)
    EXISTING_USER=$(grep "username =" "$INSTALL_DIR/user-config.nix" | cut -d'"' -f2)
    EXISTING_NAME=$(grep "fullName =" "$INSTALL_DIR/user-config.nix" | cut -d'"' -f2)
    EXISTING_EMAIL=$(grep "email =" "$INSTALL_DIR/user-config.nix" | cut -d'"' -f2)
    EXISTING_TIMEZONE=$(grep "timezone =" "$INSTALL_DIR/user-config.nix" | cut -d'"' -f2)
    EXISTING_LOCALE=$(grep "locale =" "$INSTALL_DIR/user-config.nix" | cut -d'"' -f2)

    if [ -n "$EXISTING_USER" ]; then
        echo -e "${GREEN}Found existing configuration:${NC}"
        echo "  Username: $EXISTING_USER"
        echo "  Name:     $EXISTING_NAME"
        echo "  Email:    $EXISTING_EMAIL"
        echo "  Timezone: $EXISTING_TIMEZONE"
        echo "  Locale:   $EXISTING_LOCALE"
        echo ""
        
        echo -n "Reuse this configuration? (Y/n) "
        read -n 1 REPLY < /dev/tty
        echo ""
        
        if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
            USER_NAME="$EXISTING_USER"
            USER_FULLNAME="$EXISTING_NAME"
            USER_EMAIL="$EXISTING_EMAIL"
            USER_TIMEZONE="$EXISTING_TIMEZONE"
            USER_LOCALE="$EXISTING_LOCALE"
            USE_EXISTING_CONFIG=true
        fi
    fi
fi

if [ "$USE_EXISTING_CONFIG" != "true" ]; then
    echo -e "${CYAN}Let's configure your system${NC}"
    echo ""

    while [ -z "${USER_NAME:-}" ]; do
        echo -n "Your username: "
        read USER_NAME < /dev/tty
        if [ -z "$USER_NAME" ]; then
            echo -e "${RED}Username cannot be empty${NC}"
        fi
    done

    while [ -z "${USER_FULLNAME:-}" ]; do
        echo -n "Your full name: "
        read USER_FULLNAME < /dev/tty
        if [ -z "$USER_FULLNAME" ]; then
            echo -e "${RED}Name cannot be empty${NC}"
        fi
    done

    while [ -z "${USER_EMAIL:-}" ]; do
        echo -n "Your email: "
        read USER_EMAIL < /dev/tty
        if [ -z "$USER_EMAIL" ]; then
            echo -e "${RED}Email cannot be empty${NC}"
        fi
    done

    # Timezone
    echo ""
    echo -e "${CYAN}Timezone (press Enter for default: Africa/Johannesburg)${NC}"
    echo -n "Timezone: "
    read USER_TIMEZONE < /dev/tty
    USER_TIMEZONE=${USER_TIMEZONE:-"Africa/Johannesburg"}

    # Locale
    echo -e "${CYAN}Locale (press Enter for default: en_ZA.UTF-8)${NC}"
    echo -n "Locale: "
    read USER_LOCALE < /dev/tty
    USER_LOCALE=${USER_LOCALE:-"en_ZA.UTF-8"}
fi

echo ""

# Host selection
while true; do
    echo -e "${CYAN}Which machine is this?${NC}"
    echo "1) work"
    echo "2) home"
    echo -n "Enter choice (1 or 2): "
    read choice < /dev/tty
    
    case $choice in
        1) HOST="work"; break ;;
        2) HOST="home"; break ;;
        *) echo -e "${RED}Invalid choice${NC}"; echo "" ;;
    esac
done

echo ""
echo -e "${GREEN}Configuration:${NC}"
echo "  Username: $USER_NAME"
echo "  Name:     $USER_FULLNAME"
echo "  Email:    $USER_EMAIL"
echo "  Timezone: $USER_TIMEZONE"
echo "  Locale:   $USER_LOCALE"
echo "  Host:     $HOST"
echo ""

echo -n "Continue with installation? (y/N) "
read -n 1 REPLY < /dev/tty
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Installation cancelled."
    exit 0
fi

# Backup existing configuration
if [ -d "$INSTALL_DIR" ]; then
    BACKUP_DIR="${INSTALL_DIR}.backup.$(date +%Y%m%d-%H%M%S)"
    echo -e "${YELLOW}Backing up existing config to $BACKUP_DIR${NC}"
    sudo mv "$INSTALL_DIR" "$BACKUP_DIR"
fi

# Clone repository using nix-shell with git
echo -e "${YELLOW}Cloning configuration from $REPO_URL${NC}"
nix-shell -p git --run "sudo git clone $REPO_URL $INSTALL_DIR"

# Generate hardware config
echo -e "${YELLOW}Generating hardware configuration...${NC}"
sudo nixos-generate-config --show-hardware-config | sudo tee "$INSTALL_DIR/hosts/hardware-$HOST.nix" > /dev/null

# Generate user configuration file
echo -e "${YELLOW}Generating user configuration...${NC}"

sudo tee "$INSTALL_DIR/user-config.nix" > /dev/null << USERCONFIG
# Auto-generated by install.sh - DO NOT COMMIT TO PUBLIC REPO
# Generated on: $(date)
{
  username = "$USER_NAME";
  fullName = "$USER_FULLNAME";
  email = "$USER_EMAIL";
  timezone = "$USER_TIMEZONE";
  locale = "$USER_LOCALE";
}
USERCONFIG

echo -e "${GREEN}Created user-config.nix${NC}"

# Make scripts executable
sudo chmod +x "$INSTALL_DIR/scripts/"*.sh

# Add user-config.nix to git (required for flakes to see it)
echo -e "${YELLOW}Adding configuration to git...${NC}"
nix-shell -p git --run "cd $INSTALL_DIR && sudo git config user.email '$USER_EMAIL' && sudo git config user.name '$USER_FULLNAME' && sudo git add user-config.nix hosts/hardware-$HOST.nix && sudo git commit -m 'Add local configuration'"

# Update flake inputs to get latest versions with correct hashes
echo -e "${YELLOW}Updating flake inputs...${NC}"
nix-shell -p git --run "cd $INSTALL_DIR && sudo nix flake update --option experimental-features 'nix-command flakes'"

# Commit the lock file
nix-shell -p git --run "cd $INSTALL_DIR && sudo git add flake.lock && sudo git commit -m 'Update flake.lock' || true"

# Run garbage collection to free up space for build
echo -e "${YELLOW}Cleaning up old generations to free space...${NC}"
sudo nix-collect-garbage -d || true

# Build and switch using nix-shell with git (required for flake evaluation)
echo ""
echo -e "${YELLOW}Building system configuration...${NC}"
echo -e "${BLUE}This will download and build all packages (may take 10-30 minutes)${NC}"
echo ""

if nix-shell -p git --run "sudo nixos-rebuild switch --flake $INSTALL_DIR#$HOST --option experimental-features 'nix-command flakes'"; then
    echo ""
    echo -e "${GREEN}======================================${NC}"
    echo -e "${GREEN}  Installation complete!${NC}"
    echo -e "${GREEN}======================================${NC}"
    echo ""
    echo -e "${BLUE}Next steps:${NC}"
    echo "1. Set your password: passwd"
    echo "2. Log out of current session"
    echo "3. Select 'COSMIC' at the login screen"
    echo "4. Log in and enjoy!"
    echo ""
    echo -e "${YELLOW}Useful commands:${NC}"
    echo "  Rebuild:        sudo nixos-rebuild switch --flake /etc/nixos#$HOST"
    echo "  Update:         cd /etc/nixos && sudo nix flake update && sudo nixos-rebuild switch --flake /etc/nixos#$HOST"
    echo "  Export COSMIC:  /etc/nixos/scripts/sync-cosmic.sh export"
    echo ""
    echo -e "${CYAN}Private dotfiles:${NC}"
    echo "  If you have a private dotfiles repo, clone it and run the installer:"
    echo "  git clone git@github.com:JulianPasco/dotfiles-private.git ~/dotfiles-private"
    echo "  cd ~/dotfiles-private && ./install-dotfiles.sh"
    echo ""
else
    echo ""
    echo -e "${RED}Installation failed!${NC}"
    echo "Check the error messages above."
    echo ""
    echo "Common fixes:"
    echo "  - Run: sudo nix flake update (in /etc/nixos)"
    echo "  - Check hardware-$HOST.nix has correct filesystem UUIDs"
    echo ""
    exit 1
fi
